version: "3"
services:
  api:
    container_name: api
    image: pabloamoradev/vrx_api_authenticate:latest
    network_mode: host
    restart: on-failure
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ./public:/app/public
      - ./data:/app/data
      - ./src/global:/app/src/global
